Beginning C++23: Chapter 13
Apress/beginning-cpp23 pull request #11
Opened 2023-03-12 15:47 UTC by Peter-VanWeert

2023-03-18 13:43 UTC, MarcGregoire requested changes

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_01/Box.cpp
>  {
This comment is about line 20.
The op* is multiplying lenght, width and height with factor, but the exercise asks for "to produce a new object that has a height that is n times the original object" So, only the height should be multiplied.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_02/Box.cpp
>  {
See previous comment. exercise 1 asked "to produce a new object that has a height that is n times the original object" so in both op*(double) and op*(double, box) only height should be multiplied.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_03/Box.cpp
> +import std;
Same comment as before about "to produce a new object that has a height that is n times the original object"

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_04/Soln13_04.cpp
>  /*
Comment for line 6: rephrase C++20?

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_06/Box.cppm
> +  bool operator!() const { return volume() == 0; }
Why did you add op!() one?
It all works with just the conversion operator below.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_06/Box.cppm
> +  bool operator!() const { return volume() == 0; }
Ah, I just read the next exercise (7)... it's kinda on purpose

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_08/Rational.cppm
Several operators that define a copy are not using uniform init.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_08/Rational.cppm
>    }
Typo towards end of file, it says myRationale, should be without ending e.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_10/Box.cppm
> +  int compare(const Box& box) const
This is not the same implementation as Ex13_11 which the exercise text refers to.

2023-03-18 13:43 UTC, MarcGregoire commented on Examples/Modules/Chapter 13/Ex13_05/Box.cpp
>  {
This comment is about line 12. Technically, it's not a "new" box. You're modifying the current box.

2023-03-18 13:43 UTC, MarcGregoire commented on Examples/Modules/Chapter 13/Ex13_11/Box.cpp
> +  // New object has larger length and width, and sum of heights
Technically, it's not a "new" box. You're modifying the current box.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_04/Box.cppm
> +  auto operator<=>(const Box& otherBox) const
Up to now, it was always explicitly std::partial_ordering.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_04/Box.cppm
> +  auto operator<=>(double otherVolume) const
Up to now, it was always explicitly std::partial_ordering.

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_06/Box.cppm
> +  auto operator<=>(const Box& otherBox) const
See previous comments.
Same for op<=>(double)

2023-03-18 13:43 UTC, MarcGregoire commented on Exercises/Modules/Chapter 13/Soln13_09/Box.cpp
> +  // New object has larger length and width, and sum of heights
Technically, it's not a "new" box. You're modifying the current box.

2023-03-18 17:08 UTC, MarcGregoire requested changes

2023-03-18 17:08 UTC, MarcGregoire commented on Examples/Modules/Chapter 13/Ex13_12B/Message.cppm
>  {
This comment is about line 27:
return one.swap(other);
this should just be:
one.swap(other);

2023-06-18 14:05 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 13/Soln13_06/Box.cppm
> +  bool operator!() const { return volume() == 0; }
It wasn't on purpose originally. But now it is :-)

2023-06-18 14:09 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 13/Soln13_04/Box.cppm
> +  auto operator<=>(const Box& otherBox) const
No matter...

2023-06-18 14:12 UTC, merged

2023-06-18 14:14 UTC, Peter-VanWeert commented
(Forgot to push my fixes before merging, but they're on main...)