Beginning C++23: Chapter 16
Apress/beginning-cpp23 pull request #13
Opened 2023-04-10 16:09 UTC by Peter-VanWeert

2023-05-03 19:03 UTC, MarcGregoire requested changes

2023-05-03 19:03 UTC, MarcGregoire commented on Exercises/Modules/Chapter 16/Soln16_06/Soln16_06.cpp
>      for (auto& customer : customers)
for (const auto& customer : customers)

2023-05-03 19:03 UTC, MarcGregoire commented on Exercises/Modules/Chapter 16/Soln16_06/Soln16_06.cpp
> -}
Use explicit constructors in DB_RAII.cppm?

2023-05-03 19:03 UTC, MarcGregoire commented on Exercises/Modules/Chapter 16/Soln16_06/Soln16_06.cpp
> -}
Mark DBConnectionRAII and DBQueryResultRAII destructors as virtual or mark the classes as final.

2023-06-18 15:00 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 16/Exer16_06/Customer.cpp
>    , m_city{ city }
Uhm... Because the exercise is "The Exer16_06 directory contains a small program that calls upon a C interface to a fictitious database system [...] To fix the resource leaks in our program [...] we’d like you to create and use two small RAII classes [...] you may not even have to change much of the remainder of the code!"?

2023-06-18 15:20 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 16/Soln16_06/Soln16_06.cpp
> -}
Having no explicit constructors for RAII classes is conventional. I never do the "virtual or final" thingy in this book (or in real life) (and neither does, say, the Standard Library).

2023-06-18 15:22 UTC, merged

2023-06-18 16:19 UTC, MarcGregoire commented on Exercises/Modules/Chapter 16/Exer16_06/Customer.cpp
>    , m_city{ city }
Ok, fair enough, I thought the text saying Exer16_06 was also wrong. But, apparently not.

2023-06-18 16:22 UTC, MarcGregoire commented on Exercises/Modules/Chapter 16/Soln16_06/Soln16_06.cpp
> -}
Then we'll have to agree to disagree.