Beginning C++23: Chapter 19
Apress/beginning-cpp23 pull request #16
Opened 2023-04-30 13:04 UTC by Peter-VanWeert

2023-05-06 10:18 UTC, MarcGregoire requested changes

2023-05-06 10:18 UTC, MarcGregoire commented on Exercises/Modules/Chapter 19/Soln19_02/Soln19_02.cpp
> +  std::println("Integers to be sorted: {:n:2}", numbers);
Cannot verify this kind of output yet. Not yet supported.

2023-05-06 10:18 UTC, MarcGregoire commented on Exercises/Modules/Chapter 19/Soln19_04/Soln19_04.cpp
> +  std::println("All numbers: {:n}", numbers);
Cannot verify this kind of output yet. Not yet supported.

2023-05-06 10:18 UTC, MarcGregoire commented on Exercises/Modules/Chapter 19/Soln19_05/DeliveryTruck.cppm
>  {
This example uses std::function<>, but in DeliveryTruck.cpp you write:
`m_callbacks.push_back(std::move(callback));   // Do not copy!`

So, maybe this is a good use case to use the new std::move_only_function<>? As in:
`using Callback = std::move_only_function<void(SharedBox)>`

Because then you can't even make a copy of a callback.

2023-06-22 15:15 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 19/Ex19_02/Ex19_02.cpp
> +  std::vector<int> numbers{ 91, 18, 92, 22, 13, 43 };
The back? I added `<int>` back for cosmetic reasons, no doubt, to be analogous with the `<std::string>` below (yes, I know, string literals would've been another way...). Always a sucker for good looking code...

2023-06-22 15:16 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 19/Soln19_02/Soln19_02.cpp
> +  std::println("Integers to be sorted: {:n:2}", numbers);
You verify by looking at the standard...?

2023-06-22 15:21 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 19/Soln19_05/DeliveryTruck.cppm
>  {
`std::move_only_function` is not necessarily intended to make uncopyable function objects, but more to allow encapsulating other uncopyable function objects... So it's certainly not the perfect use case... But, still, in this particular case, there is some merit to it: would be strange to have copyable delivery trucks, and then getting callbacks from the copy as well...

2023-06-22 15:37 UTC, MarcGregoire commented on Exercises/Modules/Chapter 19/Soln19_02/Soln19_02.cpp
> +  std::println("Integers to be sorted: {:n:2}", numbers);
Of course, that's what I do. Just couldn't test it hands-on yet, at that time...

PS: just figured out few days ago that Clang 16 has support for formatting ranges. Not yet std::print(), but std::format() works with ranges! For example: https://gcc.godbolt.org/z/caYqe1cnG

2023-06-22 15:53 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 19/Ex19_05/Ex19_05.cpp
> +  auto longer = [](std::string_view x, std::string_view y) { return x.length() > y.length(); };
I never use it in my daily coding, only for this bug. It's ugly, especially for lambdas... But you're right, consistency...

2023-06-22 15:54 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 19/Ex19_05/Ex19_05.cpp
> +  std::println("Alphabetically last name: {}", *findOptimum(names, alpha));
That was a mistake...

2023-06-22 16:05 UTC, merged