Beginning C++23: Chapter 20
Apress/beginning-cpp23 pull request #19
Opened 2023-05-20 12:07 UTC by Peter-VanWeert

2023-05-27 09:47 UTC, MarcGregoire requested changes

2023-05-27 09:47 UTC, MarcGregoire commented on Examples/Modules/Chapter 20/Ex20_12A/Ex20_12A.cpp
> +  auto print_result = [&boxes] (auto result)
Why no longer uniform init?

2023-05-27 09:47 UTC, MarcGregoire commented on Examples/Modules/Chapter 20/Ex20_19/Ex20_19.cpp
> +  auto view = std::views::iota(1, 11); // Could be any view/range...
There are lots of places in this function where you can use uniform init.

2023-05-27 09:47 UTC, MarcGregoire commented on Examples/Modules/Chapter 20/Ex20_19/Ex20_19.cpp
> +  v3.insert(v3.begin(), set.begin(), set.end());
"v3.begin() + 5"
to match the v1.begin() + 5 above.

2023-05-27 09:47 UTC, MarcGregoire commented on Exercises/Modules/Chapter 20/Soln20_15/Soln20_15.cpp
> +  std::cout << std::format("My new box, {:.2}, is fabulous!", box);
Why not:
`std::println("My new box, {:.2}, is fabulous!", box);`

2023-05-27 09:47 UTC, MarcGregoire commented on Exercises/Modules/Chapter 20/Soln20_16/BoxFormatter.cppm
> +
Use Uniform init in this code?

2023-05-27 09:47 UTC, MarcGregoire commented on Exercises/Modules/Chapter 20/Soln20_17/BoxFormatter.cppm
> +      double_format.erase(double_format.end() - 1); // Take out the 'n'
Or:
`double_format.pop_back();`

2023-05-27 09:47 UTC, MarcGregoire commented on Exercises/Modules/Chapter 20/Soln20_17/BoxFormatter.cppm
> +
Use Uniform init in this code?

2023-05-27 09:47 UTC, MarcGregoire commented on Exercises/Modules/Chapter 20/Soln20_17/BoxFormatter.cppm
> +export module box.formatter;
Very nice new exercises about custom formatters!

2023-06-24 14:14 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 20/Ex20_05/Ex20_05.cpp
> +  Words words = extractWords(text);
I'll never get used to it... Good thing that it also makes no difference 99% of the times, and the times where it does make a difference it's 99% an irrelevant one :-)

2023-06-24 14:17 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 20/Ex20_12A/Ex20_12A.cpp
> +  auto print_result = [&boxes] (auto result)
But... but... It's so ugly for lambda expressions...

2023-06-24 14:19 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 20/Soln20_15/Soln20_15.cpp
> +  std::cout << std::format("My new box, {:.2}, is fabulous!", box);
Otherwise you wouldn't have any work...

2023-06-24 14:26 UTC, merged