Beginning C++23: Appendix A
Apress/beginning-cpp23 pull request #20
Opened 2023-06-04 09:53 UTC by Peter-VanWeert

2023-06-10 10:05 UTC, MarcGregoire requested changes

2023-06-10 10:05 UTC, MarcGregoire commented on Examples/NoModules/CMakeLists.txt
> +cmake_minimum_required (VERSION 3.10)
Did you add this CMakeLists.txt on purpose?
Can't review it as I don't know cmake.

2023-06-18 15:26 UTC, Peter-VanWeert commented on Examples/NoModules/CMakeLists.txt
> +cmake_minimum_required (VERSION 3.10)
This was  by accident. And better not review, because this globbeldyglob is hardly going to be good use of CMake :-)

2023-06-24 15:35 UTC, Peter-VanWeert commented on Exercises/NoModules/Appendix A/SolnA_03/SolnA_03.cpp
>    // Advanced use. This was no requirement of the exercise,
Removed it instead... No need to be smarter than requested...

2023-06-24 15:42 UTC, merged