Beginning C++23: Chapter 17
Apress/beginning-cpp23 pull request #21
Opened 2023-06-04 11:17 UTC by Peter-VanWeert

2023-06-08 17:45 UTC, MarcGregoire requested changes

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_01/Array.cppm
> +  Array(std::size_t size);             // Constructor
Was explicit before in the chapter.

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_01/Soln17_01.cpp
>  // class template. Using copy-and-swap for a memory-safe push_back().
exception-safe i.o. memory_safe?

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_02/Soln17_02.cpp
> +  auto pair = Pair<int, std::string>(122, "abc");
uniform init?

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_03/Soln17_03.cpp
> +  for (std::size_t i {}; i <= max_index; ++i)       // Create count entries in numbers array
Wrong comment.

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_04/LinkedList.cppm
>  class LinkedList
the assignment operator is defined as:
`LinkedList& operator=(LinkedList list);`
which is not typical.
It usually is:
`LinkedList& operator=(const LinkedList& list);`
Also update its implementation to use the standard copy-and-swap idiom:
```
template<typename T>
LinkedList<T>& LinkedList<T>::operator=(const LinkedList& list)
{
	auto copy{ list };
	swap(copy);
	return *this;
}
```

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_04/Soln17_04.cpp
> +// Exercise 17-5 Exercising the LinkedList template class
17-4

2023-06-08 17:45 UTC, MarcGregoire commented on Exercises/Modules/Chapter 17/Soln17_04/LinkedList.cppm
>  class LinkedList
Same comment for LinkedList in Soln17_05

2023-06-08 17:45 UTC, MarcGregoire commented on Examples/Modules/Chapter 17/Ex17_02/Ex17_02.cpp
> +      std::println("\nout_of_range exception object caught! {}", ex.what());
I might have mentioned this before, but you can still use the error stream with std::print()/println().
For example:
`std::println(std::cerr, "\nout_of_range exception object caught! {}", ex.what());`

2023-06-24 12:53 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 17/Ex17_02/Array.cppm
> +  std::size_t getSize() const noexcept { return m_size; } // Accessor for size
There's too many of them. Nothing wrong with some variation.

2023-06-24 13:01 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 17/Ex17_04B/Stack.cppm
>  Stack<T>::Stack(const Stack& stack)
Interestingly, removing reset() even changes the behaviour for the better (if the destructor throws)...

2023-06-24 13:16 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 17/Soln17_04/LinkedList.cppm
>  class LinkedList
This variation is equally good. But I've added a comment acknowledging that. 

(As per https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Copy-and-swap it's even a better variation... Better for performance, better for combining move operator, ... Something to keep in mind for the next edition!)

2023-06-24 13:16 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 17/Ex17_02/Ex17_02.cpp
> +      std::println("\nout_of_range exception object caught! {}", ex.what());
You have mentioned it several times before. And as I always: I know, but I don't cover `std::cerr` anymore in the book.

2023-06-24 13:19 UTC, merged