Begining C++23: Chapter 8
Apress/beginning-cpp23 pull request #24
Opened 2023-06-25 09:09 UTC by Peter-VanWeert

2023-06-27 12:04 UTC, MarcGregoire requested changes

2023-06-27 12:04 UTC, MarcGregoire commented on Examples/Modules/Chapter 08/Ex8_18.cpp
> +	return n == 0 ? 1 : x * power(x, n - 1);
You usually use 2 spaces instead of tabs for indentation.

2023-06-29 14:13 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 08/Ex8_07.cpp
>  void change_it_by_pointer(double* reference_to_it);    // Pass pointer (by value)
Nothing technically about it, that was a full blown mistake...

2023-06-29 14:23 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 08/Soln8_06.cpp
>    }
I have passed fixed-size arrays on several occasions. But it's rare. I've turned it into a bonus exercise: that way we have both, an exercise on passing arrays by reference, and one to modernize old, crappy code. Plus, it's less work for me now ;-)

2023-06-29 16:10 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 08/Ex8_18.cpp
> +	std::array<int, static_cast<std::size_t>(Size::THREE)> a3;  // Ok: enumerator
Yeah, but then it becomes a function call, and I'm only explaining function calls later in the current narrative... So I'll pass... Could add a note later on, but it 'd only be distracting...

2023-07-02 09:27 UTC, merged