Beginning C++23: Chapter 5
Apress/beginning-cpp23 pull request #6
Opened 2023-01-08 16:22 UTC by Peter-VanWeert

2023-01-22 10:04 UTC, MarcGregoire requested changes

2023-01-22 10:04 UTC, MarcGregoire commented on Examples/Modules/Chapter 05/Ex5_07.cpp
> +      std::print("------");
Or something like:
std::print("{:->6}", "");
this makes it clearer that it’s printing 6 dashes, otherwise you need to manually count them.

2023-01-22 10:04 UTC, MarcGregoire commented on Examples/Modules/Chapter 05/Ex5_07A.cpp
> +      std::print("------");
Or something like:
std::print("{:->6}", "");
this makes it clearer that it’s printing 6 dashes, otherwise you need to manually count them.

2023-01-22 10:04 UTC, MarcGregoire commented on Examples/Modules/Chapter 05/Ex5_14.cpp
> +    std::print("--------");
Or something like:
std::print("{:->8}", "");
this makes it clearer that it’s printing 8 dashes, otherwise you need to manually count them.

2023-01-22 10:04 UTC, MarcGregoire commented on Examples/Modules/Chapter 05/Ex5_14.cpp
> +    std::print("--------");
Or something like:
std::print("{:->8}", "");
this makes it clearer that it’s printing 8 dashes, otherwise you need to manually count them.

2023-01-22 10:04 UTC, MarcGregoire commented
Done with review.

2023-06-04 12:18 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_03.cpp
> +  std::size_t values_current_line {};    // Number of outputs on current line
Now both are using `unsigned`...

2023-06-04 12:19 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_03B.cpp
> +  const size_t values_per_line {3}; // Outputs per line
Now both are using `unsigned`...

2023-06-04 12:25 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_07.cpp
> +  int table {};             // Table size
Because `std::size_t`, first and foremost, is an alias defined to express a data size (as in: the result of `sizeof()`, or the size of containers). Because that made it an alias large enough also to represent the size of arrays, and because you tend to compare indices with the size, it is also used for array and sequential container indexes. But that does not mean you need to use it everywhere. Anywhere else the natural thing to do is just to use `int` or `unsigned int` in 99% of the cases, and occasionally other integer types if smaller or larger numbers are required, or other aliases if fixed sizes are required. Either way, there's zero reason or advantage in over-using `std::size_t`. So I see no reason to do so. 

All `size_t`s I replaced are left-overs from older editions of the book, btw, I would never write those to begin with. So I also don't get why you keep saying I'm switching "back" to `int`? I'm making progress here, no regressions...

2023-06-04 12:26 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_10.cpp
> +  unsigned int vowels {};       // Count of vowels
Because this is neither a size nor an index I'm moving forward, not back, and getting rid of the `std::size_t`...

2023-06-04 12:26 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_11.cpp
> +  unsigned choice {};
Because this is neither a size nor an index...

2023-06-04 12:29 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_14.cpp
> +  const unsigned wt_count {1 + (max_wt - min_wt) / wt_step};
Because this is neither a size nor an index. Why do you keep insisting to use `std::size_t` everywhere?

2023-06-04 12:30 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_06.cpp
> +  unsigned int count{};                          // Counts the number of input values
Nope...

2023-06-04 12:30 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 05/Soln5_02.cpp
>    while (true)
Why?

2023-06-04 12:31 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 05/Soln5_06.cpp
> +  unsigned count {};              // Number of output values
As always: because these are neither sizes nor indexes, so I'm moving away (and forward) from using `std::size_t`...

2023-06-04 12:32 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 05/Soln5_07.cpp
> +  std::vector<unsigned> product_id;
A better question: why would one ever use `std::size_t` for product ids?

2023-06-04 12:33 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 05/Soln5_07.cpp
> +    unsigned id {};
Because that is not what the `std::size_t` alias is for...

2023-06-04 12:33 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_07.cpp
> +      std::print("------");
True. But then I have to explain it. So let's keep things simple ;-)

2023-06-04 12:33 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 05/Ex5_14.cpp
> +    std::print("--------");
True. But then I have to explain it. So let's keep things simple ;-)

2023-06-04 12:34 UTC, merged

2023-06-08 08:06 UTC, MarcGregoire commented on Examples/Modules/Chapter 05/Ex5_07.cpp
> +  int table {};             // Table size
Fair enough.