Begining C++23: Chapter 6
Apress/beginning-cpp23 pull request #7
Opened 2023-01-21 13:13 UTC by Peter-VanWeert

2023-01-29 11:38 UTC, MarcGregoire requested changes
Done with review.

2023-01-29 11:38 UTC, MarcGregoire commented on Exercises/Modules/Chapter 06/Soln6_01.cpp
> -  const size_t n {50};
Why did you switch to int instead of size_t on several places in this code?

2023-01-29 11:38 UTC, MarcGregoire commented on Exercises/Modules/Chapter 06/Soln6_02.cpp
> -  const size_t n {50};
Why did you switch to int instead of size_t on several places in this code?

2023-01-29 11:38 UTC, MarcGregoire commented on Exercises/Modules/Chapter 06/Soln6_03.cpp
> +    leads to infinity if neither of the operands is infinity.
There's something grammatically wrong with this sentence.

2023-01-29 11:38 UTC, MarcGregoire commented on Exercises/Modules/Chapter 06/Soln6_03.cpp
> +    The solution we went with was in our solution is the use of a larger integer type, unsigned long long.
Too many "solution".
Maybe:
"The solution we went with is to use of a larger integer type, unsigned long long." ?

2023-01-29 11:38 UTC, MarcGregoire commented on Exercises/Modules/Chapter 06/Soln6_05.cpp
> +  for (unsigned long long i {}; i < n; ++i) // See Soln6_03 for the use of unsigned long long
The comment " // See Soln6_03 for the use of unsigned long long" doesn't belong to this for loop but to the previous for loop.

2023-06-04 14:45 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 06/Ex6_05.cpp
> +  const unsigned max {100};      // Number of primes required
As always: because it's neither a data size nor an index. See the PR for Chapter 5 for a longer motivation.

2023-06-04 14:46 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 06/Ex6_06.cpp
> +  unsigned max {};        // Number of primes required
Only for sizes (it's in the name: *size*_t) or indices. See the Chapter 5 PR for a longer motivation...

2023-06-04 14:51 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 06/Soln6_01.cpp
> -  const size_t n {50};
Same as always + a loop further down where std::size_t would've been dangerous...

2023-06-04 14:56 UTC, merged