Beginning C++23: Chapter 7
Apress/beginning-cpp23 pull request #8
Opened 2023-02-01 20:17 UTC by Peter-VanWeert

2023-02-03 15:16 UTC, MarcGregoire requested changes

2023-02-03 15:16 UTC, MarcGregoire commented on Exercises/Modules/Chapter 07/Soln7_02.cpp
> +  std::vector<size_t> counts;                                // Words counts (same order as words)
std:: for all size_t in this code?

2023-02-03 15:16 UTC, MarcGregoire commented on Exercises/Modules/Chapter 07/Soln7_08A.cpp
> +// See Soln7_08A for an alternate solution that first splits the text into a vector of words.
This is 8A, you probably mean 8B.

2023-02-03 15:16 UTC, MarcGregoire commented on Exercises/Modules/Chapter 07/Soln7_08B.cpp
> +// Exercise 7-8. Testing whether something is a tautogram.
Something is not right with this solution.
When I run it with:
Truly tautograms triumph trumpeting trills to trounce terrible travesties
the it says "It is a "near tautogram", though, as most longer words do start with the letter T"

2023-02-03 15:16 UTC, MarcGregoire commented on Exercises/Modules/Chapter 07/Soln7_08B.cpp
> +// Exercise 7-8. Testing whether something is a tautogram.
It's choking on the "to"

2023-06-04 15:03 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 07/Ex7_06.cpp
> +  unsigned count{};                                     // Number of printed strings
Because I was kicked out of the std::size_t fan club. This'll teach 'm. See the PR of Chapter 5 for an alternative motivation.

2023-06-04 15:08 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 07/Ex7_05.cpp
> +  size_t index{};            // String index
Yes, this one, yes...

2023-06-04 15:09 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 07/Ex7_05.cpp
> +  size_t count{};            // Count of substring occurrences
Whoops, should not have been size_t anymore ;-)

2023-06-08 08:09 UTC, MarcGregoire commented on Examples/Modules/Chapter 07/Ex7_06.cpp
> +  unsigned count{};                                     // Number of printed strings
🤣😂

2023-07-08 11:55 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 07/Soln7_01.cpp
> +    // (Note: we'll try to remember to add this annoyance as a hint in the next edition...)
Lol. The one part I leave until after the draft submission (Chapter 7 exercises)... Next edition, for sure!

2023-07-08 12:17 UTC, merged