Beginning C++23: Chapter 11
Apress/beginning-cpp23 pull request #9
Opened 2023-03-05 13:51 UTC by Peter-VanWeert

2023-03-09 08:05 UTC, MarcGregoire requested changes
Done with review.

2023-03-09 08:05 UTC, MarcGregoire commented on Examples/Modules/Chapter 11/Ex11_06/Ex11_06.cpp
>  }
The text is still saying something about the removed call to math::square()

2023-03-09 08:05 UTC, MarcGregoire commented on Examples/Modules/Chapter 11/Ex11_06A/Ex11_06A.cpp
>  }
Add back the call to math::square()?

2023-03-09 08:05 UTC, MarcGregoire commented on Examples/Modules/Chapter 11/Ex11_06B/Ex11_06B.cpp
>  }
Add back the call to math::square()?

2023-03-09 08:05 UTC, MarcGregoire commented on Examples/Modules/Chapter 11/Ex11_08/Ex11_08.cpp
> +  std::println("This should be 5: {}", hypotenuse(3, 4));
Add back the call to math::square()?

2023-03-11 10:22 UTC, Peter-VanWeert commented on Exercises/Modules/Chapter 11/Soln11_06/words.cppm
>  export namespace w = words;
The `export using namespace words;` below should actually work...

2023-06-11 13:07 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 11/Ex11_03/Ex11_03.cpp
> +  const std::size_t num_numerals = to_roman(1234).size();  // 8 numerals ("MCCXXXIV")
Should be auto. std::size_t is not visible... technically...

2023-06-11 13:08 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 11/Ex11_03/Ex11_03.cpp
>    auto roman{ to_roman(567) };
Now both say 789...

2023-06-11 13:09 UTC, Peter-VanWeert commented on Examples/Modules/Chapter 11/Ex11_03/Ex11_03.cpp
> +  auto first_X = roman.find('X');  // 2 (index of first X in "DLXVII")
"first X" also made no sense anymore. Hence the switch to 789.

2023-06-11 13:21 UTC, merged